### ISSUE TITLE
send soap receive json

### ISSUE THREAD

**Issue by yoavst** [joaocruz04/JSoap#1]
Is there a way to use this library when you receive json?

**Comment by joaocruz04** [comment]
Hi, 
This lib is prepared for SOAP only. If you want json, there's a great lib for that: gson.

Best, 
João

**Comment by yoavst** [comment]
no, I mean I send soap to the server, but receive json. is there a way to use this library this way?

**Comment by joaocruz04** [comment]
At the moment it cannot do that. But that's a simple thing to add, I'll add a return method to get the raw response by Friday, if you're interested.

João

**Comment by yoavst** [comment]
thanks.

**Comment by joaocruz04** [comment]
Meanwhile you can override the method "onDebugMessage" on the SoapCallback. I think I put there the full request and response from the server so until I add the new method you could use it.

João



No dia 14/01/2015, às 16:44, Yoav Sternberg <notifications@github.com> escreveu:

**Comment by joaocruz04** [comment]
The new version is already out (1.0.1). If you pass null in the output class at the SOAPManager.get method, you will receive a string at the onSuccess callback containing the raw response. Hope this helps.
