### ISSUE TITLE
Is it possible change "extand SOAPSerializable" to "implements" ?

### ISSUE THREAD

**Issue by likaci** [joaocruz04/JSoap#2]
thank for this wonderful repo.
I am using an orm libray and JSoap. The orm libray must extand it's class too.
So is it possible to change extand to implement
Thanks.

**Comment by joaocruz04** [comment]
Thanks for the feedback.
I'll address this issue today or at most tomorrow. I'll be in touch :)

**Comment by joaocruz04** [comment]
I think I have found a solution. You won't need to implement or extend the SOAPSerializable / SOAPDeserializable anymore! The only requirement is to have the proper annotations :)
I'm almost there, but I need you to give me at least 24h so I can test this better before releasing.

Cheers!
João

**Comment by likaci** [comment]
Very exciting and looking forward to your solution.
Thanks very much.

**Comment by joaocruz04** [comment]
Hi likaci,
I've just released 1.0.2. Your domain classes are now SOAPSerializable and SOAPDeserializable "free" :) Please let me know if everything went fine.

João

**Comment by joaocruz04** [comment]
Well I'll close this since there are no objections :)
